export const GET_LEARN_ERROR_DETAIL = 'GET_LEARN_ERROR_DETAIL';

export const CLOSE_LEARN_PAGE_ERROR_MODAL_DETAIL = 'CLOSE_LEARN_PAGE_ERROR_MODAL_DETAIL';

//VIDEO
export const GET_VIDEO_LEARN_DETAIL = "GET_VIDEO_LEARN_DETAIL";

export const GET_VIDEO_SUCCESS_LEARN_DETAIL = "GET_VIDEO_SUCCESS_LEARN_DETAIL";

export const GET_VIDEO_ERROR_LEARN_DETAIL = "GET_VIDEO_ERROR_LEARN_DETAIL";

export const OPEN_MODAL_VIDEO_LEARN_DETAIL = "OPEN_MODAL_VIDEO_LEARN_DETAIL";

export const CLOSE_MODAL_VIDEO_LEARN_DETAIL = "CLOSE_MODAL_VIDEO_LEARN_DETAIL";


//LEARN DETAIL
export const SET_ID_LEARN_DETAIL = 'SET_ID_LEARN_DETAIL';

export const GET_LEARN_DETAIL_DETAIL = 'GET_LEARN_DETAIL_DETAIL';

export const GET_LEARN_DETAIL_ERROR = 'GET_LEARN_DETAIL_ERROR';

export const GET_LEARN_DETAIL_SUCCESS_DETAIL = 'GET_LEARN_DETAIL_SUCCESS_DETAIL';


export const CLOSE_MODAL_IMAGE_DETAIL = 'CLOSE_MODAL_IMAGE_DETAIL';

export const OPEN_MODAL_IMAGE_DETAIL = 'OPEN_MODAL_IMAGE_DETAIL';

export const SET_LINK_IMAGE_DETAIL = 'SET_LINK_IMAGE_DETAIL';