export const GET_NEW_FEED = "GET_NEW_FEED";
export const GET_NEW_FEED_SUCCESS = "GET_NEW_FEED_SUCCESS";
export const GET_NEW_FEED_ERROR = "GET_NEW_FEED_ERROR";
export const CLOSE_GET_NEW_FEED_ERROR_MODAL = "CLOSE_GET_NEW_FEED_ERROR_MODAL";
export const SET_FETCHING_DATA = 'SET_FETCHING_DATA';

export const GET_SECTION_NEWS = "GET_SECTION_NEWS";
export const GET_SECTION_NEWS_SUCCESS = "GET_SECTION_NEWS_SUCCESS";
export const GET_SECTION_NEWS_ERROR = "GET_SECTION_NEWS_ERROR";

export const GET_VIDEO = "GET_VIDEO";
export const GET_VIDEO_SUCCESS = "GET_VIDEO_SUCCESS";
export const GET_VIDEO_ERROR = "GET_VIDEO_ERROR";
export const OPEN_MODAL_VIDEO = "OPEN_MODAL_VIDEO";
export const CLOSE_MODAL_VIDEO = "CLOSE_MODAL_VIDEO";

export const GET_CONNECTION = "GET_CONNECTION";
export const GET_CONNECTION_SUCCESS = "GET_CONNECTION_SUCCESS";
export const GET_CONNECTION_ERROR = "GET_CONNECTION_ERROR";

export const POST_STATUS = "POST_STATUS";
export const POST_STATUS_SUCCESS = "POST_STATUS_SUCCESS";
export const POST_STATUS_ERROR = "POST_STATUS_ERROR";

export const OPEN_MODAL_DELETE = "OPEN_MODAL_DELETE";
export const CLOSE_MODAL_DELETE = "CLOSE_MODAL_DELETE";
export const ARGEE_DELETE = "ARGEE_DELETE";
export const ARGEE_DELETE_SUCCESS = "ARGEE_DELETE_SUCCESS";

export const LIKE_ASK = "LIKE_ASK";
export const LIKE_ASK_SUCCESS = "LIKE_ASK_SUCCESS";
export const LIKE_ASK_ERROR = "LIKE_ASK_ERROR";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

export const GET_COMMENT = "GET_COMMENT";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_ERROR = "GET_COMMENT_ERROR";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

export const CLOSE_MODAL_IMAGE = 'CLOSE_MODAL_IMAGE';
export const OPEN_MODAL_IMAGE = 'OPEN_MODAL_IMAGE';
export const SET_LINK_IMAGE = 'SET_LINK_IMAGE';