export const GET_LIST_LEARN = 'GET_LIST_LEARN';

export const GET_LEARN_SUCCESS = 'GET_LEARN_SUCCESS';

export const GET_LEARN_ERROR = 'GET_LEARN_ERROR';

export const CLOSE_LEARN_PAGE_ERROR_MODAL = 'CLOSE_LEARN_PAGE_ERROR_MODAL';

export const SET_FETCHING_DATA = 'SET_FETCHING_DATA';

//VIDEO
export const GET_VIDEO_LEARN = "GET_VIDEO_LEARN";

export const GET_VIDEO_SUCCESS_LEARN = "GET_VIDEO_SUCCESS_LEARN";

export const GET_VIDEO_ERROR_LEARN = "GET_VIDEO_ERROR_LEARN";

export const OPEN_MODAL_VIDEO_LEARN = "OPEN_MODAL_VIDEO_LEARN";

export const CLOSE_MODAL_VIDEO_LEARN = "CLOSE_MODAL_VIDEO_LEARN";
