export const GET_TOP_SEARCH = 'GET_TOP_SEARCH';

export const GET_TOP_SEARCH_ERROR = 'GET_TOP_SEARCH_ERROR';

export const GET_TOP_SEARCH_SUCCESS = 'GET_TOP_SEARCH_SUCCESS';

export const OPEN_MODAL_SEACH = 'OPEN_MODAL_SEACH';

export const SET_KEYWORD_SEARCH = 'SET_KEYWORD_SEARCH';

export const CLOSE_MODAL_SEARCH = 'CLOSE_MODAL_SEARCH';

export const CLOSE_MODAL_SEARCH_ERROR = 'CLOSE_MODAL_SEARCH_ERROR';