export const REQUEST_RESET_PASSWORD_REQUESTING = 'REQUEST_RESET_PASSWORD_REQUESTING';  
export const REQUEST_RESET_PASSWORD_SUCCESS = 'REQUEST_RESET_PASSWORD_SUCCESS'; 
export const REQUEST_RESET_PASSWORD_ERROR = 'REQUEST_RESET_PASSWORD_ERROR';    
export const REQUEST_RESET_PASSWORD_ERROR_CATCH = 'REQUEST_RESET_PASSWORD_ERROR_CATCH';
export const REQUEST_RESET_PASSWORD_FORM_ERRORS = 'REQUEST_RESET_PASSWORD_FORM_ERRORS'; 
export const REQUEST_RESET_PASSWORD_EMAIL_VALID = 'REQUEST_RESET_PASSWORD_EMAIL_VALID'; 
export const REQUEST_RESET_PASSWORD_FORM_VALID = 'REQUEST_RESET_PASSWORD_FORM_VALID'; 
export const REQUEST_RESET_PASSWORD_CLOSE_ERROR_MODAL = 'REQUEST_RESET_PASSWORD_CLOSE_ERROR_MODAL'; 
export const REQUEST_RESET_PASSWORD_CLOSE_SUCCESS_MODAL = 'REQUEST_RESET_PASSWORD_CLOSE_SUCCESS_MODAL';
export const REQUEST_RESET_PASSWORD_OPEN_SUCCESS_MODAL = 'REQUEST_RESET_PASSWORD_OPEN_SUCCESS_MODAL'; 

