export const GET_LIST_LEARN = 'GET_LIST_LEARN';

export const GET_LEARN_SUCCESS = 'GET_LEARN_SUCCESS';

export const GET_LEARN_ERROR = 'GET_LEARN_ERROR';

export const CLOSE_LEARN_PAGE_ERROR_MODAL_LIST = 'CLOSE_LEARN_PAGE_ERROR_MODAL_LIST';

export const SET_FETCHING_DATA = 'SET_FETCHING_DATA';


export const CLOSE_MODAL_IMAGE = 'CLOSE_MODAL_IMAGE';

export const OPEN_MODAL_IMAGE = 'OPEN_MODAL_IMAGE';

export const SET_LINK_IMAGE = 'SET_LINK_IMAGE';