export const RESET_PASSWORD_REQUESTING = 'RESET_PASSWORD_REQUESTING';  
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'; 
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';    
export const RESET_PASSWORD_ERROR_CATCH = 'RESET_PASSWORD_ERROR_CATCH';
export const RESET_PASSWORD_HIDDEN = 'RESET_PASSWORD_HIDDEN'; 
export const RESET_PASSWORD_RE_HIDDEN = 'RESET_PASSWORD_RE_HIDDEN'; 
export const RESET_PASSWORD_FORM_ERRORS = 'RESET_PASSWORD_FORM_ERRORS'; 
export const RESET_PASSWORD_PASSWORD_VALID = 'RESET_PASSWORD_PASSWORD_VALID'; 
export const RESET_PASSWORD_RE_PASSWORD_VALID = 'RESET_PASSWORD_RE_PASSWORD_VALID'; 
export const RESET_PASSWORD_FORM_VALID = 'RESET_PASSWORD_FORM_VALID'; 
export const RESET_PASSWORD_CLOSE_SUCCESS_MODAL = 'RESET_PASSWORD_CLOSE_SUCCESS_MODAL';
export const RESET_PASSWORD_OPEN_SUCCESS_MODAL = 'RESET_PASSWORD_OPEN_SUCCESS_MODAL'; 
export const RESET_PASSWORD_CLOSE_ERROR_MODAL = 'RESET_PASSWORD_CLOSE_ERROR_MODAL'

